---
title: "Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require(ClustIRR)
require(ggplot2)
require(patchwork)

```


# Create input data

```{r}
data("CD8")

# data sample d0: 500 unique CDR3s drawn from reference database (CD8) with 10^4 CDR3s
set.seed(seed = 1234)
d_0 <- data.frame(CDR3b = CD8[sample(x = 1:nrow(CD8), size = 500, replace = FALSE),])


# data sample d1: enrich motif 'RQWW'
d_1 <- d_0
substr(x = d_1$CDR3b[1:20], start = 6, stop = 9) <- "RQWW"


# data sample d2: clonal expansion with two similar clones of hdist 1
d_2 <- d_1
clone_a <- data.frame(CDR3b = rep(x = "CATSRAAKPDGLAALETQYF", times = 15))
clone_b <- data.frame(CDR3b = rep(x = "CATSRAAKPDGLAALSTQYF", times = 15))
d_2 <- rbind(d_2, clone_a)
d_2 <- rbind(d_2, clone_b)

data_ref      <- CD8
data_ref_u    <- unique(CD8)
data_sample   <- d_1
#data_sample_u <- unique(d_1) # already unique
data_sample_e <- d_2
data_sample_e_u <- unique(d_2)

rm(CD8, clone_a, clone_b, d_0, d_1, d_2)

```


# OvE Ground truth

```{r, ove_ground_truth}
# Compute OvE for data
# (f_sample / n_sample) / (f_ref / n_ref)
# f_ref/sample = motifs of a certain length found in ref / sample
# n_ref/sample = motif count of a certain length present in ref / sample

# motif length
motif_length <- 4

# find motifs
f_ref        <- stringdist::qgrams(data_ref$CDR3b,        q=motif_length)
f_ref_u      <- stringdist::qgrams(data_ref_u$CDR3b,      q=motif_length)
f_sample     <- stringdist::qgrams(data_sample$CDR3b,     q=motif_length)
f_sample_e   <- stringdist::qgrams(data_sample_e$CDR3b,   q=motif_length)
f_sample_e_u <- stringdist::qgrams(data_sample_e_u$CDR3b, q=motif_length)


# convert to data frames
f_ref        <- f_ref[1,]
f_ref        <- data.frame(motif=names(f_ref), 
                           f_ref=as.numeric(f_ref))
f_ref_u      <- f_ref_u[1,]
f_ref_u      <- data.frame(motif=names(f_ref_u), 
                           f_ref_u=as.numeric(f_ref_u))
f_sample     <- f_sample[1,]
f_sample     <- data.frame(motif=names(f_sample), 
                           f_sample=as.numeric(f_sample))
f_sample_e   <- f_sample_e[1,]
f_sample_e   <- data.frame(motif=names(f_sample_e), 
                           f_sample_e_u=as.numeric(f_sample_e))
f_sample_e_u <- f_sample_e_u[1,]
f_sample_e_u <- data.frame(motif=names(f_sample_e_u), 
                           f_sample_e_u=as.numeric(f_sample_e_u))

# find motif counts
f_ref$n_ref               <- sum(f_ref$f_ref)
f_ref_u$n_ref_u           <- sum(f_ref_u$f_ref_u)
f_sample$n_sample         <- sum(f_sample$f_sample)
f_sample_e$n_sample_e     <- sum(f_sample_e$f_sample_e)
f_sample_e_u$n_sample_e_u <- sum(f_sample_e_u$f_sample_e_u)

# consolidate to motifs found in sample
f_ref     <- f_ref  [f_ref$motif   %in% f_sample$motif,     ]
f_ref_u   <- f_ref_u[f_ref_u$motif %in% f_sample$motif,     ]
f_ref_e   <- f_ref  [f_ref$motif   %in% f_sample_e$motif,   ]
f_ref_e_u <- f_ref_u[f_ref_u$motif %in% f_sample_e_u$motif, ]

gt_motifs     <- merge(f_sample,     f_ref,   by = "motif", all = TRUE)
gt_motifs_u   <- merge(f_sample,     f_ref_u, by = "motif", all = TRUE)
gt_motifs_e   <- merge(f_sample_e,   f_ref,   by = "motif", all = TRUE)
gt_motifs_e_u <- merge(f_sample_e_u, f_ref_u, by = "motif", all = TRUE)

# replace f_ref NA with 0 and n_ref NA with n_ref
gt_motifs[is.na(gt_motifs[, "f_ref"]), "f_ref"] <- 0
gt_motifs[is.na(gt_motifs[, "n_ref"]), "n_ref"] <- gt_motifs$n_ref[1]

gt_motifs_u[is.na(gt_motifs_u[, "f_ref_u"]), "f_ref_u"] <- 0
gt_motifs_u[is.na(gt_motifs_u[, "n_ref_u"]), "n_ref_u"] <- 
  gt_motifs_u$n_ref_u[1]

gt_motifs_e[is.na(gt_motifs_e[, "f_ref"]), "f_ref"] <- 0
gt_motifs_e[is.na(gt_motifs_e[, "n_ref"]), "n_ref"] <- 
  gt_motifs_e$n_ref[1]

gt_motifs_e_u[is.na(gt_motifs_e_u[, "f_ref_u"]), "f_ref_u"] <- 0
gt_motifs_e_u[is.na(gt_motifs_e_u[, "n_ref_u"]), "n_ref_u"] <- 
  gt_motifs_e_u$n_ref_u[1]

# compute ove
gt_motifs$ove <- (gt_motifs$f_sample / gt_motifs$n_sample) / 
  (gt_motifs$f_ref / gt_motifs$n_ref)

gt_motifs_u$ove <- (gt_motifs_u$f_sample / gt_motifs_u$n_sample) / 
  (gt_motifs_u$f_ref_u / gt_motifs_u$n_ref_u)

gt_motifs_e$ove <- (gt_motifs_e$f_sample_e / gt_motifs_e$n_sample_e) / 
  (gt_motifs_e$f_ref / gt_motifs_e$n_ref)

gt_motifs_e_u$ove <- (gt_motifs_e_u$f_sample_e_u / gt_motifs_e_u$n_sample_e_u) / 
  (gt_motifs_e_u$f_ref_u / gt_motifs_e_u$n_ref_u)


rm(f_ref, f_ref_u, f_ref_e, f_ref_e_u, f_sample, f_sample_e, f_sample_e_u)

```

# Prepare input parameters

```{r create_parameters}
# v1 + v2 + v3
ks <- motif_length
cores <- parallel::detectCores()

control_input <- list(
  B = 1000,
  global_max_dist = 1,
  local_max_fdr = 0.01,
  local_min_ove = 2,
  local_min_o = 3,
  trim_flank_aa = 0,
  low_mem = FALSE,
  global_pairs = NULL)

```

# Cluster with ClustIRR versions

```{r run_clustirr}
# data_sample with inserted motifs but without clonal expansion
out_v1 <- cluster_irr(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 1,
                control = control_input)

out_v2 <- cluster_irr(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 2,
                control = control_input)

out_v3 <- cluster_irr(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 3,
                control = control_input)

# data_sample with inserted motifs and clonal expansion
out_v1_e <- cluster_irr(data_sample = data_sample_e,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 1,
                control = control_input)

out_v2_e <- cluster_irr(data_sample = data_sample_e,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 2,
                control = control_input)

out_v3_e <- cluster_irr(data_sample = data_sample_e,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 3,
                control = control_input)

```


# Prepare results


```{r prep_results}
o1  <- out_v1$clust$CDR3b$local$m
o2  <- out_v2$clust$CDR3b$local$m
o3  <- out_v3$clust$CDR3b$local$m
o1e <- out_v1_e$clust$CDR3b$local$m
o2e <- out_v2_e$clust$CDR3b$local$m
o3e <- out_v3_e$clust$CDR3b$local$m

# rename all columns except "motif"
names(o1)[names(o1) != "motif"] <- 
  paste(names(o1)[names(o1) != "motif"], "v1", sep="_")
names(o2)[names(o2) != "motif"] <- 
  paste(names(o2)[names(o2) != "motif"], "v2", sep="_")
names(o3)[names(o3) != "motif"] <- 
  paste(names(o3)[names(o3) != "motif"], "v3", sep="_")
names(o1e)[names(o1e) != "motif"] <- 
  paste(names(o1e)[names(o1e) != "motif"], "v1_e", sep="_")
names(o2e)[names(o2e) != "motif"] <- 
  paste(names(o2e)[names(o2e) != "motif"], "v2_e", sep="_")
names(o3e)[names(o3e) != "motif"] <- 
  paste(names(o3e)[names(o3e) != "motif"], "v3_e", sep="_")

names(gt_motifs)[names(gt_motifs) != "motif"] <- 
  paste(names(gt_motifs)[names(gt_motifs) != "motif"], "gt", sep="_")
names(gt_motifs_e)[names(gt_motifs_e) != "motif"] <- 
  paste(names(gt_motifs_e)[names(gt_motifs_e) != "motif"], "gt_e", sep="_")

# reduce to one big table
res <- Reduce(function (...) { merge(..., by = "motif", all = TRUE) },
                       list(o1, o2, o3, o1e, o2e, o3e, 
                            gt_motifs, gt_motifs_e)) 

# compute delta values for ove
res$delta_ove_v1 <- (res$ove_v1 - res$ove_gt)
res$delta_ove_v2 <- (res$ove_v2 - res$ove_gt)
res$delta_ove_v3 <- (res$ove_v3 - res$ove_gt)
res$delta_ove_v1_e <- (res$ove_v1_e - res$ove_gt_e)
res$delta_ove_v2_e <- (res$ove_v2_e - res$ove_gt_e)
res$delta_ove_v3_e <- (res$ove_v3_e - res$ove_gt_e)

# compute delta values for f_sample
res$delta_f_sample_v1 <- (res$f_sample_v1 - res$f_sample_gt)
res$delta_f_sample_v2 <- (res$f_sample_v2 - res$f_sample_gt)
res$delta_f_sample_v3 <- (res$f_sample_v3 - res$f_sample_gt)
res$delta_f_sample_v1_e <- (res$f_sample_v1_e - res$f_sample_e_gt)
res$delta_f_sample_v2_e <- (res$f_sample_v2_e - res$f_sample_e_gt)
res$delta_f_sample_v3_e <- (res$f_sample_v3_e - res$f_sample_e_gt)

# compute delta values for n_sample
res$delta_n_sample_v1 <- NA
res$delta_n_sample_v2 <- (res$n_sample_v2 - res$n_sample_gt)
res$delta_n_sample_v3 <- (res$n_sample_v3 - res$n_sample_gt)
res$delta_n_sample_v1_e <- NA
res$delta_n_sample_v2_e <- (res$n_sample_v2_e - res$n_sample_e_gt)
res$delta_n_sample_v3_e <- (res$n_sample_v3_e - res$n_sample_e_gt)

# compute delta values for f_ref
res$delta_f_ref_v1 <- (res$mean_f_ref_v1 - res$f_ref_gt)
res$delta_f_ref_v2 <- (res$f_ref_v2 - res$f_ref_gt)
res$delta_f_ref_v3 <- (res$f_ref_v3 - res$f_ref_gt)
res$delta_f_ref_v1_e <- (res$mean_f_ref_v1_e - res$f_ref_gt_e)
res$delta_f_ref_v2_e <- (res$f_ref_v2_e - res$f_ref_gt_e)
res$delta_f_ref_v3_e <- (res$f_ref_v3_e - res$f_ref_gt_e)

# compute delta values for n_ref
res$delta_n_ref_v1 <- NA
res$delta_n_ref_v2 <- (res$n_ref_v2 - res$n_ref_gt)
res$delta_n_ref_v3 <- (res$n_ref_v3 - res$n_ref_gt)
res$delta_n_ref_v1_e <- NA
res$delta_n_ref_v2_e <- (res$n_ref_v2_e - res$n_ref_gt_e)
res$delta_n_ref_v3_e <- (res$n_ref_v3_e - res$n_ref_gt_e)

rm(o1, o2, o3, o1e, o2e, o3e, gt_motifs, gt_motifs_e)

```

# Check Delta Counts

```{r check_deltas}

# ove
ove_v1 <- res[(!is.na(res$delta_ove_v1) & res$delta_ove_v1 != 0),
              c("motif", "ove_v1", "ove_gt", "delta_ove_v1")]
ove_v2 <- res[(!is.na(res$delta_ove_v2) & res$delta_ove_v2 != 0),
              c("motif", "ove_v2", "ove_gt", "delta_ove_v2")]
ove_v3 <- res[(!is.na(res$delta_ove_v3) & res$delta_ove_v3 != 0),
              c("motif", "ove_v3", "ove_gt", "delta_ove_v3")]

ove_v1e <- res[(!is.na(res$delta_ove_v1_e) & res$delta_ove_v1_e != 0),
              c("motif", "ove_v1_e", "ove_gt_e", "delta_ove_v1_e")]
ove_v2e <- res[(!is.na(res$delta_ove_v2_e) & res$delta_ove_v2_e != 0),
              c("motif", "ove_v2_e", "ove_gt_e", "delta_ove_v2_e")]
ove_v3e <- res[(!is.na(res$delta_ove_v3_e) & res$delta_ove_v3_e != 0),
              c("motif", "ove_v3_e", "ove_gt_e", "delta_ove_v3_e")]

# f_sample
fs_v1 <- res[(!is.na(res$delta_f_sample_v1) & res$delta_f_sample_v1 != 0), 
             c("motif", "f_sample_v1", "f_sample_gt")]
fs_v2 <- res[(!is.na(res$delta_f_sample_v2) & res$delta_f_sample_v2 != 0), 
             c("motif", "f_sample_v2", "f_sample_gt")]
fs_v3 <- res[(!is.na(res$delta_f_sample_v3) & res$delta_f_sample_v3 != 0), 
             c("motif", "f_sample_v3", "f_sample_gt")]

fs_v1e <- res[(!is.na(res$delta_f_sample_v1_e) & res$delta_f_sample_v1_e != 0), 
             c("motif", "f_sample_v1_e", "f_sample_e_gt_e")]
fs_v2e <- res[(!is.na(res$delta_f_sample_v2_e) & res$delta_f_sample_v2_e != 0), 
             c("motif", "f_sample_v2_e", "f_sample_e_gt_e")]
fs_v3e <- res[(!is.na(res$delta_f_sample_v3) & res$delta_f_sample_v3 != 0), 
             c("motif", "f_sample_v3_e", "f_sample_e_gt_e")]

# n_sample
ns_v2 <- res[(!is.na(res$delta_n_sample_v2) & res$delta_n_sample_v2 != 0), 
             c("motif", "n_sample_v2", "n_sample_gt")]
ns_v3 <- res[(!is.na(res$delta_n_sample_v3) & res$delta_n_sample_v3 != 0), 
             c("motif", "n_sample_v3", "n_sample_gt")]
ns_v2e <- res[(!is.na(res$delta_n_sample_v2_e) & res$delta_n_sample_v2_e != 0), 
             c("motif", "n_sample_v2_e", "n_sample_e_gt_e")]
ns_v3e <- res[(!is.na(res$delta_n_sample_v3) & res$delta_n_sample_v3 != 0), 
             c("motif", "n_sample_v3_e", "n_sample_e_gt_e")]

# f_ref
fr_v1 <- res[(!is.na(res$delta_f_ref_v1) & res$delta_f_ref_v1 != 0), 
             c("motif", "mean_f_ref_v1", "f_ref_gt")]
fr_v2 <- res[(!is.na(res$delta_f_ref_v2) & res$delta_f_ref_v2 != 0), 
             c("motif", "f_ref_v2", "f_ref_gt")]
fr_v3 <- res[(!is.na(res$delta_f_ref_v3) & res$delta_f_ref_v3 != 0), 
             c("motif", "f_ref_v3", "f_ref_gt")]

fr_v1e <- res[(!is.na(res$delta_f_ref_v1_e) & res$delta_f_ref_v1_e != 0), 
             c("motif", "mean_f_ref_v1_e", "f_ref_gt_e")]
fr_v2e <- res[(!is.na(res$delta_f_ref_v2_e) & res$delta_f_ref_v2_e != 0), 
             c("motif", "f_ref_v2_e", "f_ref_gt_e")]
fr_v3e <- res[(!is.na(res$delta_f_ref_v3) & res$delta_f_ref_v3 != 0), 
             c("motif", "f_ref_v3_e", "f_ref_gt_e")]

# n_ref
nr_v2 <- res[(!is.na(res$delta_n_ref_v2) & res$delta_n_ref_v2 != 0), 
             c("motif", "n_ref_v2", "n_ref_gt")]
nr_v3 <- res[(!is.na(res$delta_n_ref_v3) & res$delta_n_ref_v3 != 0), 
             c("motif", "n_ref_v3", "n_ref_gt")]
nr_v2e <- res[(!is.na(res$delta_n_ref_v2_e) & res$delta_n_ref_v2_e != 0), 
             c("motif", "n_ref_v2_e", "n_ref_gt_e")]
nr_v3e <- res[(!is.na(res$delta_n_ref_v3) & res$delta_n_ref_v3 != 0), 
             c("motif", "n_ref_v3_e", "n_ref_gt_e")]

df <- data.frame(version = c("1","2","3"),
                 ove = c(nrow(ove_v1), nrow(ove_v2), nrow(ove_v3)),
                 ove_e = c(nrow(ove_v1e), nrow(ove_v2e), nrow(ove_v3e)),
                 f_sample = c(nrow(fs_v1), nrow(fs_v2), nrow(fs_v3)),
                 f_sample_e = c(nrow(fs_v1e), nrow(fs_v2e), nrow(fs_v3e)),
                 n_sample = c(NA, nrow(ns_v2), nrow(ns_v3)),
                 n_sample_e = c(NA, nrow(ns_v2e), nrow(ns_v3e)),
                 n_ref = c(NA, nrow(nr_v2), nrow(nr_v3)),
                 n_ref_e = c(NA, nrow(nr_v2e), nrow(nr_v3e))
                 )

knitr::kable(df, caption="number of rows that are different from ground truth")

```
# Investigate found motif

```{r found_motifs}

m_v1 <- out_v1$clust$CDR3b$local$m[out_v1$clust$CDR3b$local$m$pass==TRUE,]
m_v2 <- out_v2$clust$CDR3b$local$m[out_v2$clust$CDR3b$local$m$pass==TRUE,]
m_v3 <- out_v3$clust$CDR3b$local$m[out_v3$clust$CDR3b$local$m$pass==TRUE,]

m_v1_e <- out_v1_e$clust$CDR3b$local$m[
  out_v1_e$clust$CDR3b$local$m$pass==TRUE,]
m_v2_e <- out_v2_e$clust$CDR3b$local$m[
  out_v2_e$clust$CDR3b$local$m$pass==TRUE,]
m_v3_e <- out_v3_e$clust$CDR3b$local$m[
  out_v3_e$clust$CDR3b$local$m$pass==TRUE,]

df <- data.frame(version = c("1","2","3"),
                 no_exp = c(nrow(m_v1), nrow(m_v2), nrow(m_v3)),
                 exp = c(nrow(m_v1_e), nrow(m_v2_e), 
                                      nrow(m_v3_e)))

knitr::kable(df, caption="found motifs")


```


## Check if implanted motif "RQWW" is found

```{r local_motifs}
# inspect local motif enrichment results
knitr::kable(m_v1, caption="v1")
knitr::kable(m_v2, caption="v2")
knitr::kable(m_v3, caption="v3")
knitr::kable(m_v1_e, caption="v1 exp")
knitr::kable(m_v2_e, caption="v2 exp")
knitr::kable(m_v3_e, caption="v3 exp")

```
## Compare p-values and fdr

```{r p_fdr}
# fdr        <= local_max_fdr
# ove        >= local_min_ove
# f_sample   >= local_min_o

# thresholds
df <- data.frame(local_max_fdr = control_input$local_max_fdr,
                 local_min_ove = control_input$local_min_ove,
                 local_min_o   = control_input$local_min_o)

knitr::kable(df, caption="selection thresholds")

# subset selected motifs
r <- res[(res$pass_v1==TRUE & !is.na(res$pass_v1) ) |
           (res$pass_v2==TRUE & !is.na(res$pass_v2) ) |
           (res$pass_v3==TRUE & !is.na(res$pass_v3) ),
         c("motif", "pass_v1", "pass_v2", "pass_v3",
           "p_v1", "p_value_v2", "p_value_v3", 
           "fdr_v1", "fdr_v2",   "fdr_v3", 
           #"mean_f_ref_v1", "f_ref_v2", "f_ref_v3", 
           "f_sample_v1", "f_sample_v2", "f_sample_v3",
           "ove_v1", "ove_v2", "ove_v3")]
# sort
r <- r[order(-r$pass_v2),]

# inspect local motif enrichment results
knitr::kable(r, caption="p-value / fdr comparison")



```

## Check if global sequences "CATSRAAKPDGLAALETQYF" and "CATSRAAKPDGLAALSTQYF" are found

```{r global_motifs}
# inspect which CDR3bs are globally similar

df <- data.frame(version = c("1","2","3"),
                 no_exp = c(nrow(m_v1), nrow(m_v2), nrow(m_v3)),
                 exp = c(nrow(m_v1_e), nrow(m_v2_e), 
                                      nrow(m_v3_e)))

knitr::kable(out_v3$clust$CDR3b$global, caption="without clonal expansion")
knitr::kable(out_v3_e$clust$CDR3b$global, caption="with clonal expansion")


```

```{r cleanup}

rm(df, fr_v1, fr_v1e, fr_v2, fr_v2e, fr_v3, fr_v3e,
   fs_v1, fs_v1e, fs_v2, fs_v2e, fs_v3, fs_v3e,
   m_v1, m_v2, m_v3, m_v1_e, m_v2_e, m_v3_e,
   nr_v2, nr_v2e, nr_v3, nr_v3e,
   ns_v2, ns_v2e, ns_v3, ns_v3e,
   ove_v1, ove_v1e, ove_v2, ove_v2e, ove_v3, ove_v3e)

```