---
title: "Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require(gliphR)
require(ggplot2)
require(patchwork)
```

This vignette is only designated for testing gliphR1. <br>


# Create input data

An artificial clonal expansion of 100 vs 1 sequences of a HIV specific
CDR3b sequence is created as input.

```{r create_input_data}

# set seed for reproducibility 
set.seed(1234)

# HIV specific CDR3b sequence, taken from last research project
# TODO insert correct source / database
# CASSETGGTYEQYF TRBV6-1 	TRBJ2-7 	
hiv_expansion <- c(CDR3b = "CASSETGGTYEQYF", 
                   TRBV = "TRBV6-1", 
                   TRBJ = "TRBJ2-7 ")

data("hs_CD8_ref")
data_ref <- hs_CD8_ref[, 1:3]

# insert single CDR3b sequence into reference repertoire
data_ref <- rbind(data_ref, hiv_expansion)

# sample 5000 sequences from reference repertoire
data_sample <- hs_CD8_ref[sample(x = 1:nrow(data_ref), 
                                 size = 5000, replace = FALSE), 1:3]


# create artificial expansion of 100 sequences
for(i in 0:99) {
  data_sample <- rbind(data_sample, hiv_expansion)
}



```


# Prepare input parameters

```{r create_parameters}

cores <- parallel::detectCores()

# gliphR v1
ks <- c(2, 3, 4)
B <- 1000
control_input <- list(
  B = B,
  global_max_dist = 1,
  local_max_fdr = 0.05,
  local_min_ove = 2,
  local_min_o = 3,
  trim_flank_aa = 3,
  low_mem = FALSE,
  global_pairs = NULL)


```

# Cluster with gliphR versions

```{r run_gliph}
out_v1 <- gliph(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 1,
                control = control_input)



# put in the same data for ref and sample
out_v1_i <- gliph(data_sample = data_sample,
                  data_ref = data_sample,
                  ks = ks,
                  cores = cores,
                  version = 1,
                  control = control_input)


```


# Compare results

```{r compare_results}

# prepare for visualization
e_v1 <- out_v1$clust$CDR3b$local$m
colnames(e_v1)[which(colnames(e_v1) == 'ove')]     <- 'OvE_gliphR1'
e_v1_i <- out_v1_i$clust$CDR3b$local$m
colnames(e_v1_i)[which(colnames(e_v1_i) == 'ove')] <- 'OvE_gliphR1_identical'


```


## Identical vs different input

```{r identical_vs_different, fig.width=5, fig.height=5, fig.align='center'}

# gliphR v1 test versus identical input
c_v1_i <- merge(e_v1, e_v1_i, by = "motif", all = TRUE)
c_v1_i[is.na(c_v1_i)] <- -1
g_v1 <- ggplot(c_v1_i, aes(x = OvE_gliphR1_identical, y = OvE_gliphR1)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 - identical versus different input")



g_v1


```
