---
title: "Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require(gliphR)
require(turboGliph)
require(ggplot2)
require(patchwork)
```

This vignette compares the gliphR package with the turboGliph package.


# Create input data

```{r create_input_data}

#set.seed(123)

data("hs_CD8_ref")
# ref <- base::grep(pattern = "^C.*F$",x = hs_CD8_ref$CDR3b,
#                   perl = TRUE,value = TRUE)
# ref <- data.frame(cdr3b = ref, TRBV = NA, TRBJ = NA)

data_sample <- hs_CD8_ref[sample(x = 1:nrow(hs_CD8_ref), 
                                 size = 2000, replace = FALSE), 1:3]

# create artificial expansion
for(i in 1:49) {
  data_sample <- rbind(data_sample, data_sample[1, ])
}

data_ref <- hs_CD8_ref[, 1:3]

```


# Cluster with gliphR versions

```{r run_gliph}

# prepare input parameters
ks <- c(2, 3, 4)
B <- 1000
cores <- parallel::detectCores()
control_input <- list(
  B = B,
  global_max_dist = 1,
  local_max_fdr = 0.05,
  local_min_ove = 10^2,
  local_min_o = 3,
  trim_flank_aa = 3,
  low_mem = FALSE,
  global_pairs = NULL)

# run the three versions of gliphR
out_v1 <- gliph(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 1,
                control = control_input)

out_v2 <- gliph(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 2,
                control = control_input)


out_v3 <- gliph(data_sample = data_sample,
                data_ref = data_ref,
                ks = ks,
                cores = cores,
                version = 3,
                control = control_input)

# put in the same data for ref and sample
out_v1_i <- gliph(data_sample = data_sample,
                  data_ref = data_sample,
                  ks = ks,
                  cores = cores,
                  version = 1,
                  control = control_input)

out_v2_i <- gliph(data_sample = data_sample,
                  data_ref = data_sample,
                  ks = ks,
                  cores = cores,
                  version = 2,
                  control = control_input)


out_v3_i <- gliph(data_sample = data_sample,
                  data_ref = data_sample,
                  ks = ks,
                  cores = cores,
                  version = 3,
                  control = control_input)

```

# Cluster with turboGliph versions

```{r run_turbogliph}

jan_v1 <- turboGliph::turbo_gliph(
  cdr3_sequences = data_sample,
  refdb_beta = data_ref,
  sim_depth = B,
  lcminp = 0.05,
  gccutoff = 1,
  structboundaries = FALSE,
  boundary_size = 0,
  cluster_min_size = 1,
  accept_sequences_with_C_F_start_end = TRUE
  )


jan_v2 <- turboGliph::gliph2(
    cdr3_sequences = data_sample,
    refdb_beta = data_ref,
    sim_depth = B,
    lcminp = 0.05,
    cdr3_length_freq = NULL,
    motif_distance_cutoff = 0,
    accept_sequences_with_C_F_start_end = TRUE,
    structboundaries = TRUE,
    min_seq_length = 1
    )

jan_v3 <- turboGliph::gliph_combined(
    cdr3_sequences = data_sample,
    refdb_beta = data_ref,
    lcminp = 0.05,
    lcsim_depth = B,
    motif_distance_cutoff = 0,
    accept_sequences_with_C_F_start_end = TRUE,
    structboundaries = TRUE,
    min_seq_length = 1
    )


# put in sample as ref for checking
jan_v1_i <- turboGliph::turbo_gliph(
  cdr3_sequences = data_sample,
  sim_depth = B,
  refdb_beta = data_sample,
  lcminp = 0.05,
  gccutoff = 1,
  structboundaries = FALSE,
  boundary_size = 0,
  cluster_min_size = 1,
  accept_sequences_with_C_F_start_end = TRUE
  )


jan_v2_i <- turboGliph::gliph2(
  cdr3_sequences = data_sample,
    refdb_beta = data_sample,
    lcminp = 0.05,
    cdr3_length_freq = NULL,
    sim_depth = B,
    motif_distance_cutoff = 0,
    accept_sequences_with_C_F_start_end = TRUE,
    structboundaries = TRUE,
    min_seq_length = 1
  )

jan_v3_i <- turboGliph::gliph_combined(
    cdr3_sequences = data_sample,
    refdb_beta = data_sample,
    lcminp = 0.05,
    lcsim_depth = B,
    motif_distance_cutoff = 0,
    accept_sequences_with_C_F_start_end = TRUE,
    structboundaries = TRUE,
    min_seq_length = 1
    )

```

# Compare results

```{r compare_results}

# prepare for visualization
e_v1 <- out_v1$clust$CDR3b$local$m
colnames(e_v1)[which(colnames(e_v1) == 'ove')]     <- 'OvE_gliphR1'
e_v1_i <- out_v1_i$clust$CDR3b$local$m
colnames(e_v1_i)[which(colnames(e_v1_i) == 'ove')] <- 'OvE_gliphR1_identical'
e_v2 <- out_v2$clust$CDR3b$local$m
colnames(e_v2)[which(colnames(e_v2) == 'ove')]     <- 'OvE_gliphR2'
e_v2_i <- out_v2_i$clust$CDR3b$local$m
colnames(e_v2_i)[which(colnames(e_v2_i) == 'ove')] <- 'OvE_gliphR2_identical'
e_v3 <- out_v3$clust$CDR3b$local$m
colnames(e_v3)[which(colnames(e_v3) == 'ove')]     <- 'OvE_gliphR3'
e_v3_i <- out_v3_i$clust$CDR3b$local$m
colnames(e_v3_i)[which(colnames(e_v3_i) == 'ove')] <- 'OvE_gliphR3_identical'

e_jan_v1 <- jan_v1$motif_enrichment$all_motifs
colnames(e_jan_v1)[which(colnames(e_jan_v1) == 'Motif')] <- 'motif'
colnames(e_jan_v1)[which(colnames(e_jan_v1) == 'OvE')]   <- 'OvE_turboGliph1'
e_jan_v1_i <- jan_v1_i$motif_enrichment$all_motif
colnames(e_jan_v1_i)[which(colnames(e_jan_v1_i) == 'Motif')] <- 'motif'
colnames(e_jan_v1_i)[which(colnames(e_jan_v1_i) == 'OvE')] <-
  'OvE_turboGliph1_identical'
e_jan_v2 <- jan_v2$motif_enrichment$all_motifs
colnames(e_jan_v2)[which(colnames(e_jan_v2) == 'Motif')] <- 'motif'
colnames(e_jan_v2)[which(colnames(e_jan_v2) == 'num_fold')] <- 'OvE_turboGliph2'
e_jan_v2_i <- jan_v2_i$motif_enrichment$all_motif
colnames(e_jan_v2_i)[which(colnames(e_jan_v2_i) == 'Motif')] <- 'motif'
colnames(e_jan_v2_i)[which(colnames(e_jan_v2_i) == 'num_fold')] <-
  'OvE_turboGliph2_identical'
e_jan_v3 <- jan_v3$motif_enrichment$all_motifs
colnames(e_jan_v3)[which(colnames(e_jan_v3) == 'OvE')] <- 'OvE_turboGliph3'
e_jan_v3_i <- jan_v3_i$motif_enrichment$all_motif
colnames(e_jan_v3_i)[which(colnames(e_jan_v3_i) == 'OvE')] <-
  'OvE_turboGliph3_identical'


```


## Identical vs different input

```{r identical_vs_different, fig.width=10, fig.height=10, fig.align='center'}

# gliphR v1 test versus identical input
c_v1_i <- merge(e_v1, e_v1_i, by = "motif", all = TRUE)
c_v1_i[is.na(c_v1_i)] <- -1
g_v1 <- ggplot(c_v1_i, aes(x = OvE_gliphR1_identical, y = OvE_gliphR1)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 - identical versus different input")

# gliphR v2 test versus identical input
c_v2_i <- merge(e_v2, e_v2_i, by = "motif", all = TRUE)
c_v2_i[is.na(c_v2_i)] <- -1
g_v2 <- ggplot(c_v2_i, aes(x = OvE_gliphR2_identical, y = OvE_gliphR2)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v2 - identical versus different input")

# gliphR v3 test versus identical input
c_v3_i <- merge(e_v3, e_v3_i, by = "motif", all = TRUE)
c_v3_i[is.na(c_v3_i)] <- -1
g_v3 <- ggplot(c_v3_i, aes(x = OvE_gliphR3_identical, y = OvE_gliphR3)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v3 - identical versus different input")

# turbogliph vs identical input
c_jan_v1_i <- merge(e_jan_v1, e_jan_v1_i, by = "motif", all = TRUE)
c_jan_v1_i[is.na(c_jan_v1_i)] <- -1
g_tg_v1 <- ggplot(c_jan_v1_i, aes(x = OvE_turboGliph1_identical, y = OvE_turboGliph1)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("turboGliph1 - identical versus different input")

c_jan_v2_i <- merge(e_jan_v2, e_jan_v2_i, by = "motif", all = TRUE)
c_jan_v2_i[is.na(c_jan_v2_i)] <- -1
g_tg_v2 <- ggplot(c_jan_v2_i, aes(x = OvE_turboGliph2_identical, y = OvE_turboGliph2)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("turboGliph2 - identical versus different input")

c_jan_v3_i <- merge(e_jan_v3, e_jan_v3_i, by = "motif", all = TRUE)
c_jan_v3_i[is.na(c_jan_v3_i)] <- -1
g_tg_v3 <- ggplot(c_jan_v3_i, aes(x = OvE_turboGliph3_identical, y = OvE_turboGliph3)) +
  geom_point() +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("turboGliph3 - identical versus different input")


(g_v1 + g_v2 + g_v3 ) / ( g_tg_v1 + g_tg_v2 + g_tg_v3 )

```


## gliphR versus turboGliph

```{r gliphR_turbogliph, fig.width=10, fig.height=10, fig.align='center'}

# gliphR v1 vs turboGliph 1
c_v1 <- merge(e_v1, e_jan_v1, by = "motif", all = TRUE)
c_v1[is.na(c_v1)] <- -1
g_gl1_tg1 <- ggplot(c_v1, aes(x = OvE_gliphR1, y = OvE_turboGliph1)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 vs turboGliph::turbo_gliph")


# gliphR v2 vs turboGliph 1
c_v2 <- merge(e_v2, e_jan_v1, by = "motif", all = TRUE)
c_v2[is.na(c_v2)] <- -1
g_gl2_tg1 <- ggplot(c_v2, aes(x = OvE_gliphR2, y = OvE_turboGliph1)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v2 vs turboGliph::turbo_gliph")


# gliphR v3 vs turboGliph 1
c_v3 <- merge(e_v3, e_jan_v1, by = "motif", all = TRUE)
c_v3[is.na(c_v3)] <- -1
g_gl3_tg1 <- ggplot(c_v3, aes(x = OvE_gliphR3, y = OvE_turboGliph1)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v3 vs turboGliph::turbo_gliph")



# gliphR v1 vs turboGliph 2
c_v1 <- merge(e_v1, e_jan_v2, by = "motif", all = TRUE)
c_v1[is.na(c_v1)] <- -1
g_gl1_tg2 <- ggplot(c_v1, aes(x = OvE_gliphR1, y = OvE_turboGliph2)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 vs turboGliph::gliph2")


# gliphR v2 vs turboGliph 2
c_v2 <- merge(e_v2, e_jan_v2, by = "motif", all = TRUE)
c_v2[is.na(c_v2)] <- -1
g_gl2_tg2 <- ggplot(c_v2, aes(x = OvE_gliphR2, y = OvE_turboGliph2)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v2 vs turboGliph::gliph2")


# gliphR v3 vs turboGliph 2
c_v3 <- merge(e_v3, e_jan_v2, by = "motif", all = TRUE)
c_v3[is.na(c_v3)] <- -1
g_gl3_tg2 <- ggplot(c_v3, aes(x = OvE_gliphR3, y = OvE_turboGliph2)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v3 vs turboGliph::gliph2")


# gliphR v1 vs turboGliph 3
c_v1 <- merge(e_v1, e_jan_v3, by = "motif", all = TRUE)
c_v1[is.na(c_v1)] <- -1
g_gl1_tg3 <- ggplot(c_v1, aes(x = OvE_gliphR1, y = OvE_turboGliph3)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 vs turboGliph::gliph_combined")


# gliphR v2 vs turboGliph 3
c_v2 <- merge(e_v2, e_jan_v3, by = "motif", all = TRUE)
c_v2[is.na(c_v2)] <- -1
g_gl2_tg3 <- ggplot(c_v2, aes(x = OvE_gliphR2, y = OvE_turboGliph3)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v2 vs turboGliph::gliph_combined")


# gliphR v3 vs turboGliph 3
c_v3 <- merge(e_v3, e_jan_v3, by = "motif", all = TRUE)
c_v3[is.na(c_v3)] <- -1
g_gl3_tg3 <- ggplot(c_v3, aes(x = OvE_gliphR3, y = OvE_turboGliph3)) +
  geom_point() +
  #geom_smooth(method=lm , color="blue", fill="red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v3 vs turboGliph::gliph_combined")

(g_gl1_tg1 + g_gl2_tg1 + g_gl3_tg1) / 
    (g_gl1_tg2 + g_gl2_tg2 + g_gl3_tg2) / 
    (g_gl1_tg3 + g_gl2_tg3 + g_gl3_tg3)


```


## Compare gliphR and turboGliph versions

```{r gliphR_comparison, fig.width=10, fig.height=10, fig.align='center'}

# gliphR v1 vs gliphR v2
c_v1_2 <- merge(e_v1, e_v2, by = "motif", all = TRUE)
c_v1_2[is.na(c_v1_2)] <- -1
g_gl1_gl2 <- ggplot(c_v1_2, aes(x = OvE_gliphR1, y = OvE_gliphR2)) +
  geom_point() +
  geom_smooth(method = lm , color = "blue", fill = "red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 vs gliphR v2")

# gliphR v1 vs gliphR v3
c_v1_3 <- merge(e_v1, e_v3, by = "motif", all = TRUE)
c_v1_3[is.na(c_v1_3)] <- -1
g_gl1_gl3 <- ggplot(c_v1_3, aes(x = OvE_gliphR1, y = OvE_gliphR3)) +
  geom_point() +
  geom_smooth(method = lm , color = "blue", fill = "red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v1 vs gliphR v3")

# gliphR v2 vs gliphR v3
c_v2_3 <- merge(e_v2, e_v3, by = "motif", all = TRUE)
c_v2_3[is.na(c_v2_3)] <- -1
g_gl2_gl3 <- ggplot(c_v2_3, aes(x = OvE_gliphR2, y = OvE_gliphR3)) +
  geom_point() +
  geom_smooth(method = lm , color = "blue", fill = "red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("gliphR v2 vs gliphR v3")


# turboGliph1 vs turboGliph2
tg_v1_2 <- merge(e_jan_v1, e_jan_v2, by = "motif", all = TRUE)
tg_v1_2[is.na(tg_v1_2)] <- -1
g_tg1_gl2 <- ggplot(tg_v1_2, aes(x = OvE_turboGliph1, y = OvE_turboGliph2)) +
  geom_point() +
  geom_smooth(method = lm , color = "blue", fill = "red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("turboGliph::turbo_gliph vs turboGliph::gliph2")

# turboGliph1 vs turboGliph3
tg_v1_3 <- merge(e_jan_v1, e_jan_v3, by = "motif", all = TRUE)
tg_v1_3[is.na(tg_v1_3)] <- -1
g_tg1_gl3 <- ggplot(tg_v1_3, aes(x = OvE_turboGliph1, y = OvE_turboGliph3)) +
  geom_point() +
  geom_smooth(method = lm , color = "blue", fill = "red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("turboGliph::turbo_gliph vs turboGliph::gliph_combined")

# turboGliph2 vs turboGliph3
tg_v2_3 <- merge(e_jan_v2, e_jan_v3, by = "motif", all = TRUE)
tg_v2_3[is.na(tg_v2_3)] <- -1
g_tg2_gl3 <- ggplot(tg_v2_3, aes(x = OvE_turboGliph2, y = OvE_turboGliph3)) +
  geom_point() +
  geom_smooth(method = lm , color = "blue", fill = "red") +
  geom_abline(linewidth = 0.5, color = "gray") +
  ggtitle("turboGliph::gliph2 vs turboGliph::gliph_combined")


( g_gl1_gl2 + g_gl1_gl3 + g_gl2_gl3 ) / (g_tg1_gl2 + g_tg1_gl3 + g_tg2_gl3)

```
